name: Java CI with Maven

on: [push, pull_request]  # Runs on every push and pull request

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use the Temurin JDK distribution
          java-version: '18'

      - name: Build and Run Tests
        run: mvn clean test
